version: "3"

services:
  db:
    image: mongo
    container_name: pende-mongo2
    hostname: db
    ports: 
        - "27017:27017"
    networks:
      - app-network

  pende:
    build: .
    container_name: pende
    ports:
      - "8080:8080"
    env_file:
      - "./back/.env"
    hostname: pende
    restart: always
    networks:
      - app-network
    depends_on:
      - db

networks:
  app-network:
    driver: bridge